name: Build

# Run this action during every push and pull request.
# 'workflow_call' lets this action be called by other actions.
on: [push, pull_request]

# List of jobs that this action will run.
jobs:
  # This job will build the project on ubuntu
  # using esp-idf-ci-action.
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: latest
        target: esp32
        path: '/'
        command: 'idf.py build'
    
    - name: Test ls
      run: find .
    
    # If a tag was pushed, we should publish a release
    # using the action-gh-release action.
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: '*.bin'
